### PR TITLE
Update opx_smoketest.yaml with new opx config utilites

### PR DESCRIPTION
**Pull request by Tejaswi-Goel**
Signed-off-by: Tejaswi Goel <Tejaswi_Goel@Dell.com>

### CODE REVIEW

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now 81dd699b14c88a1adac37d7c1feaf860deafb90f

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now 865e8e1d6b133b125a2988b3a29e19452bc08737

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now 1d68f215e709864aa12e3184e3ba5f49dae3ff20

**Review by madhu222 — APPROVED** [review]
Looks good to me

**Review by madhu222 — CHANGES_REQUESTED** [review]
can you please change 1host back to "{{dut}}"
And can you update the changes in smoketest in playbook directory and add to this commit?

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now 1c0b8a3bfc0e7d590c23b52a0855b7db32da43b6

**Review by madhu222 — APPROVED** [review]
LGTM

**Pull request merged**
