### PR TITLE
Added functionality scripts/playbooks for L2,Forwarding and image installation

### PR DESCRIPTION
**Pull request by madhu222**
* For L2 role, l2mac,l2_stp and l3_intra_inter playbooks are added
* For Forwarding roles, span_mirroring playbook is added
* For General, smoketest and image installation playbooks are added

Signed-off-by: Madhusudhanan Santhanam <santhanam_madhusudha@dell.com>

### CODE REVIEW

**Comment by heucke** [comment]
@madhu222 Since you're the only member of the [test team](https://github.com/orgs/open-switch/teams/test/members), this pr can't merge. Who else should be added as a required reviewer? @jeff-yin any ideas?

**Comment by jeffyin-dell** [comment]
@theucke add @Tejaswi-Goel  to the test team.

**Review by Tejaswi-Goel — DISMISSED** [review]

**Comment by madhu222** [comment]
Pull-request updated, HEAD is now 72223886c01da97e30a9489f4ac5c1224ed2f47b

**Comment by madhu222** [comment]
Pull-request updated, HEAD is now f4fcc441c84e822d080e29928bedbb014ce1ebe2

**Review by Tejaswi-Goel — APPROVED** [review]

**Pull request merged**
