### PR TITLE
Update opx_smoketest.yaml

### PR DESCRIPTION
**Pull request by Tejaswi-Goel**
Added code to run opx-config-vlan command as root

Tested the script and it works fine. 

Signed-off-by: Tejaswi Goel <Tejaswi_Goel@Dell.com>

### CODE REVIEW

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now e3ef4033c3ac8c129462dc9ae8f7c26f5e192e6b

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now 78efa31c8b7ee0a77a6da6b39a99b5ef9c364638

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now dee17e44508b1584bc61f48588225d72e79cf3e7

**Review by madhu222 — APPROVED** [review]
Looks good.

**Pull request merged**
