### PR TITLE
Add flask based GUI for OPX test infra

### PR DESCRIPTION
**Pull request by Tejaswi-Goel**
Signed-off-by: Tejaswi Goel <Tejaswi_Goel@Dell.com>

### CODE REVIEW

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now bf34f3d8087322a651138dce0823ce4510fedd71

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now 8c8c336ee036741df5236853f3f3ca63bb8feecb

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now 0da0d8aa956badc4a5e5bbe5d1cad5b1c9fc69fa

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now 13566e69046b638b2b9300b0b86c0298937b8dba

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now e45f54cb35e8198881ccd0ff394c87ae85414ae8

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now 488afc3ee74543abf1ef2b404b0baf5ce392a000

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now d3f21253ee335eaf8a3477d6403b64cd856f7ba6

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now 92ea7ed64a8031498012a1e0ed4cbb2fa5039b1e

**Review by madhu222 — APPROVED** [review]
Looks good to me

**Pull request merged**
