### PR TITLE
Update opx_smoketest.yaml

### PR DESCRIPTION
**Pull request by Tejaswi-Goel**
Signed-off-by: Tejaswi Goel <Tejaswi_Goel@Dell.com>

### CODE REVIEW

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now bc8d2baf1aa33fc8aee569c75ef16bc200609e5a

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now 2eae2a85f0ded770d8d774d1264d24d0fc0c76c1

**Review by madhu222 — APPROVED** [review]
Looks good to me.

**Comment by jeffyin-dell** [comment]
Please provide a more descriptive commit message next time!

**Comment by Tejaswi-Goel** [comment]
Changes made in this PR:
File: opx_smoketest.yaml 
1) Moving the test case to remove static route and IP address before the VLAN creation test case
2) Updating assert statements to accommodate new changes in the OPX image
3) Updating opx-show-transceivers all to opx-show-transceiver

**Pull request merged**
