### PR TITLE
Add setup.sh and update README.md

### PR DESCRIPTION
**Pull request by Tejaswi-Goel**
Signed-off-by: Tejaswi Goel <Tejaswi_Goel@Dell.com>

### CODE REVIEW

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now 966d404dfac66699ed9b250b287207e0d8b987d3

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now e43d8af47627e59e022cb002f31f7c24347ad272

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now 69f57671daffdad49be10911e50004ce0dd9bf66

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now 093d563f23bede8a677f4bff229f421b8cf4fa91

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now b37e759631637db251554158d7487e8550a31dda

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now 7865baf13843729d21f5a46ab7eba7159ed7f18c

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now 67456fd27f73d15b781eb7e7f795a555e55cf2b2

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now e8018c0da385ac969b98da4305cf388ace8fc656

**Comment by Tejaswi-Goel** [comment]
Pull-request updated, HEAD is now b94d846367f52fbc6953f875ccd262076f1a5110

**Review by madhu222 — APPROVED** [review]
You can merge it. Want to check how it looks.

**Pull request merged**
